### ISSUE TITLE
Missing Hint

### ISSUE THREAD

**Issue by Megapit** [lumpalette/SDL_cs#1]
Hi

This is not really an issue. :)
I found this repository for an little hobby project of mine. Need SDL3 in c# bindings mostly for jeystick, gamecontroller, mouse and keyboard input.
For my needs i need the "Hints" feature. So i added them for what i need.
Would like to share this work without pull request and so on.....

The work is mostly from [here](https://github.com/lithiumtoast/SDL-cs/blob/main/src/cs/production/SDL.NetCore/Generated/SDL.g.cs) but tryed to use  your naming convention.

I hope you can use it and implement the missing functions from [SDL3/hints](https://wiki.libsdl.org/SDL3/CategoryHints)

Megapit

[hints.zip](https://github.com/user-attachments/files/15969804/hints.zip)

**Comment by lumpalette** [comment]
Hi! like you have noticed, this project it's far from over. I still have to implement a lot of headers, but currently I'm doing a huge clean up to the "codebase" (mostly on how things are organized/implemented), so I can't really write bindings for new headers right now :/

As soon as I'm over with this clean up, I'll start implementing that header using you commit as a base. SDL_hints.h is a pretty big file, so it probably take a while.

**Comment by Megapit** [comment]
perfect! 
Let me know if i can help.
But c++ is far away from my knowledge :(

**Comment by lumpalette** [comment]
clean up is done!

**Comment by lumpalette** [comment]
Finally, it's done! :)
